### ISSUE TITLE
[android] FlatList support?

### ISSUE THREAD

**Issue by aksonov** [simonhoss/react-native-touch-through-view#10]
This component works well on iOS with FlatList but not for Android - I can't scroll items, underlying Map is dragged instead..

**Comment by simonhoss** [comment]
Hi @aksonov. Can you please create an example repo? Where I can see the exact issue?

**Comment by aksonov** [comment]
@simonhoss It is difficult because it uses react-native-maps and our google api key... Maybe I will try to reproduce the problem somehow else

**Comment by southerneer** [comment]
@simonhoss I work with @aksonov and I've prepared an example of our problem here: https://github.com/hippware/rnttv-test

We have a main view with pop-up views that populate from the bottom. Our experience with iOS is perfect...we can show lists in the bottom views while still interacting with the main view (a map in our real app). In Android it works fine too until we added a TextInput in the ListHeader just below TouchThroughView. When the input is focused and the keyboard is showing the TouchThroughView behavior breaks. Taps on the list go "through" to the main view behind. When the keyboard is dismissed the correct behavior is restored.

Demos are below (sorry, it's difficult to figure out when taps occur)

### on iOS
![rnttv-ios](https://user-images.githubusercontent.com/3681859/55592795-782e0d80-56ee-11e9-9233-4e36bd81f3d6.gif)

--------------------------

### on Android
![rnttv-android](https://user-images.githubusercontent.com/3681859/55592813-82500c00-56ee-11e9-9465-0f3a0296d3f2.gif)

**Comment by simonhoss** [comment]
hi @southerneer 

Thank you for your detailed response. Now I got it 😄 I think I will have a look on it on the weekend.

**Comment by simonhoss** [comment]
Hi @southerneer 

I had a look on it. Yes, there is a bug inside the react-native-touch-through-view regarding the keyboard, but android handles the keyboard different than ios and I think this is your main problem. The problem is that android pushes the view up and ios not. To fix this you can modify the AndroidManifest.xml with the following code:

```
<activity
     ...
     android:windowSoftInputMode="adjustPan"> 
</activity>
```

After that it worked well with scrolling but unfortunately the keyboard does not dismiss when scroll the FlatList. Maybe you can add a touch handler on the FlatList to solve this issue?

**Comment by southerneer** [comment]
Thanks for looking into it. I can verify that setting `windowSoftInputMode` to `adjustPan` is a workaround in that isolated case, but isn't really feasible for our "real" app where the default `adjustResize` behavior works fine for other text input fields.

I assume based on your response that there isn't a fix forthcoming anytime soon ;). I'm not an experienced Android dev so all I can offer to help is testing feedback for any changes or help with documentation. Would it make sense to PR a change to the README pointing out that this is a known issue?

**Comment by simonhoss** [comment]
First we have to find a solution how to fix the problem that the FlatList bounces up when the keyboard appears. In my opinion this is a general android problem regardless the react-native-touch-through-view. I tried it yesterday without the react-native-touch-through-view and the FlatList bounces up. 

Can you confirm this? 

If this is fixed I will have a look on the `keyboardDismissMode="on-drag"` problem.

**Comment by aksonov** [comment]
@simonhoss I don't see any problem that FlatList bounces up when the keyboard appears. The problem that touch-throught-view doesn't bounce...

**Comment by southerneer** [comment]
Hmm, if the FlatList bounces up when the keyboard appears, why wouldn't the TouchThroughView (which is inside the list header) also bounce up? As @aksonov states, everything on the screen seems to shift up with the keyboard _except_ for the TouchThroughView. Shouldn't we expect the TouchThroughView to shift with everything else? This is the bug as far as I can tell.

And for what it's worth, `keyboardDismissMode` is less concerning...most modern Android devices with soft keyboards have a dedicated dismiss keyboard button that appears along the bottom when the keyboard is active.

**Comment by Johan-dutoit** [comment]
FWIW, I am experiencing the same issue on Android, but I'm using a SectionList.
Also my issue appears *without* the keyboard (no input elements).

**Comment by Johan-dutoit** [comment]
After some further investigation, I believe the bounding box isn't calculated correctly ([TouchThroughWrapper.javaL76](https://github.com/simonhoss/react-native-touch-through-view/blob/master/android/src/main/java/com/rome2rio/android/reactnativetouchthroughview/TouchThroughWrapper.java#L76)).  

It looks like it's not taking the android header & statusbar into account?  Might be worth some more investigation that a bit more.

**Comment by simonhoss** [comment]
I made a small change. Can someone please check it out? It is published under the version `1.1.0-beta.0` in npm.

**Comment by aksonov** [comment]
@simonhoss It is much better now.. But as I can see through-view is not 'restored' now after keyboard is disappeared (so I can't access to background view), so it stops working for previous screens (without keyboard). But it works for the screen with keyboard!

**Comment by Johan-dutoit** [comment]
So far It's working perfect with my use case (i.e. no keyboard use).

**Comment by aksonov** [comment]
@simonhoss I've investigated my issue more. Looks like RNTTV doesn't work correctly for android if we have _stack_ of wrappers/through-views (several screens with RNTTV via react-navigation) ..

**Comment by southerneer** [comment]
@simonhoss thanks for looking into this. Your changes fix the bug as isolated above. It also fixes that same bug in our app but (possibly) creates another. As @aksonov mentioned our particular use case is more complex. I will try to reproduce the new bug and report back here if it looks related to this module.

**Comment by simonhoss** [comment]
Thank you for you feedback guys. It seems that the context gets lost sometimes im some particular cases. 
We have to figure out how we can register the context again.

**Comment by simonhoss** [comment]
@aksonov @southerneer I had a look again into the current example which you provides. I could not find any problem there. Can you provide a more complex example?

**Comment by aksonov** [comment]
@simonhoss Please check latest commit. There are two similar lists (BottomView1, BottomView2) and the same background view.

Steps to reproduce the issue:
1. Tap background view (you will see BottomView2)
2. Tap background view again (you will see BottomView1)
3. You are unable to scroll BottomView1 now

iOS works well.

**Comment by simonhoss** [comment]
Thank you. I will check it as soon as possible. I think I can do it after Easter. Sorry for the delay.

**Comment by simonhoss** [comment]
Hi @aksonov 

I now had time to have a look on your code. I think the problem is that you have multiple `TouchThroughWrapper` and `TouchThroughView` created at one time.

I changed the following code:

```
<BottomView1 />
{color !== defaultColor && <BottomView2 />}
```

to

```
{color === defaultColor && <BottomView1 />}
{color !== defaultColor && <BottomView2 />}
```

After that it seems to be working. Can you confirm?

**Comment by southerneer** [comment]
Hi, @simonhoss I just tried it out and I can confirm that fixes the issue as I see it on my end. Furthermore, I'm pretty sure we're rendering multiple `TouchTouchWrappers` and `TouchThroughView`s when the issue occurs in our app too. I'm working on a refactor there now and will report the results back here. Thanks so much for the help!

**Comment by simonhoss** [comment]
Ok. Please give me feedback if the refactor helped. Until that I mark this as closed and release the beta as new official version.

**Comment by southerneer** [comment]
Update: after refactoring our app to ensure only one TouchThroughView and one TouchThroughWrapper was ever rendered we were still seeing the same problem related to the keyboard. After digging into [the `android:windowSoftInputMode` options](https://developer.android.com/guide/topics/manifest/activity-element#wsoft) I tried out `android:windowSoftInputMode="stateHidden|adjustResize"` and the problem went away without any negative impacts elsewhere in the app. I'm not exactly sure _why_ that's the case, but I'm not complaining ;) Thanks again for all the help @simonhoss !
