### ISSUE TITLE
Compatibility with react-native-screens

### ISSUE THREAD

**Issue by zhigang1992** [simonhoss/react-native-touch-through-view#11]
`react-native-screens` requires the `MainActivity` to be extended from `ReactFragmentActivity` instead of `ReactActivity`.

And somehow the touches are not pass through.

**Comment by simonhoss** [comment]
Can you share an example? Maybe an example repo?

**Comment by zhigang1992** [comment]
When creating the example repo,

https://github.com/zhigang1992/reactNativeScreenAndroidTouchIssue

I realized that it's actually an issue in react-native-screens itself.

https://github.com/kmagiera/react-native-screens/issues/61

Sry for the false alarm. 😄
