### ISSUE TITLE
Multiple Touch Through View in tabNavigator does not work on Android

### ISSUE THREAD

**Issue by tboerc** [simonhoss/react-native-touch-through-view#14]
As the title says, I have a bottom tab navigator, two screens using the TouchThroughWrapper and TouchThroughView. If only the first screen is rendered (because tab navigator has lazy loading), it will work, but if the second screen is rendered, the first one will be dead, it stops from passing touches through view. Don't know what this could be, but on iOS it's working fine, so the problem is with android.

Here some info about my project:

**react-native:** 0.61.2
**react-navigation:** 4.0.10
**react-navigation-tabs:** 2.5.6
**react-native-touch-through-view:** 1.1.2

**Comment by tboerc** [comment]
With some tests, I discovered that the problem occurs when the code have more than one TouchThroughWrapper at same time, but I don't know if there is a way to use only one in my project. I want this functionality on more than one screen of the tab navigator, and after screen render on tab navigator, it stays there until I close the navigator, so the application will have two or more TouchThroughWrapper at same time.

**Comment by tboerc** [comment]
A temporary solution is only render the TouchThroughWrapper when the screen is focused, but it's not the best solution. Actually, it's really not good, the flow of the app is really bad with this.

**Comment by simonhoss** [comment]
That would be also my current workaround for you. I understand that this is not a good solution.

I try to reproduce your behavior and see what I can do.

**Comment by tboerc** [comment]
Thanks for the answer, the solution it's not the best but is usable. So if you need any help or information, maybe I can help you.

**Comment by tankers746** [comment]
I've created a PR to address this https://github.com/simonhoss/react-native-touch-through-view/pull/15

**Comment by simonhoss** [comment]
I made a beta version. Can you guys please check it out and give feedback if it works as expected?

``1.2.0-beta.0``

Thanks you @tankers746 for your help!!!

**Comment by tboerc** [comment]
Sorry for the late reply, but I tested it today and it's working flawlessly. Thanks for fixing it dude.
