### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by vascorebolo** [simonhoss/react-native-touch-through-view#8]
I've followed the steps present in the README.md, and I had it working in Android, but no in iOS. I've even manually linked the module in XCode, but it throws an error when building. Can anyone the steps for iOS?

**Comment by simonhoss** [comment]
Hi @vascocsilva what is the error on iOS? Normalls it should work with `react-native link`

**Comment by thomashermine** [comment]
Not sure if it's the same issue, but I was unable to use the lib on iOS as well by running only ```react-native link```.
As I'm using Cocoapods, I had to run ```pod install``` inside the iOS folder to make the library works :-)

**Comment by simonhoss** [comment]
@thomashermine Do you have any compile error message?

**Comment by vascorebolo** [comment]
Sorry for the late reply, I had to put the project I was on hold, meanwhile, a colleague of mine just fixed the issue, it was related to a padding that was being used, he just switched to a margin. So, it was not related to the package itself. Thanks.

**Comment by simonhoss** [comment]
Thank you for your feedback
